name: pu-pos-dev

services:
  app:
    build:
      target: builder
    command: npm run dev
    ports:
      - "8080:8080"
      - "5173:5173"
      - "9229:9229" # node debugger
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    read_only: false
    tmpfs: []
